language: node_js

node_js:
  - 6
  - 8

cache:
  directories:
    - node_modules

deploy:
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${NPM_TOKEN}
  on:
    branch: master
    node: 8
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
